development:
  adapter: postgresql
  encoding: unicode
  database: postgres_development
  pool: 5
  username: contractsavvy
  password: frescamedici

test:
  adapter: postgresql
  encoding: unicode
  database: postgres_test
  pool: 5
  username: contractsavvy
  password: frescamedici